[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/**/*"]

# Optional: Set build timeouts
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

# Optimize cache
[build.processing.images]
  compress = true